### ISSUE TITLE
Crashes on Illegal characters in path

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity-SDK/Telerik.Sitefinity.Samples.IntegrationTests#11]
![image](https://cloud.githubusercontent.com/assets/1542376/12121447/5b07beb4-b3a3-11e5-9f71-ce09ec74fd4e.png)

...I realize it might have some, but shouldn't crash

**Comment by nader-dab** [comment]
Hello,

The error above is caused due to an invalid _TraceFilePath_ argument. This argument requires a file path were the test results will be stored, for example __/TraceFilePath="C:\testResults.trx"__.

We will update the _Telerik.WebTestRunner.Cmd.exe_ tool so that a more comprehensive error is thrown in case of an ivalid argument.

**Comment by sitefinitysteve** [comment]
Would be better if no filename is specified it uses a default... Or if no param is specified users current directory with default filename.

**Comment by nader-dab** [comment]
The _Telerik.WebTestRunner.Cmd.exe_ tool was updated. 

Now you can skip the __TraceFilePath__ argument and a default __results.trx__ file will be generated in the directory from which the tool is executed.

Please note, that when using the __TraceFilePath__ argument you can also pass relative paths where the output will be generated, for example:

__/TraceFilePath="output/results.trx"__
__/TraceFilePath="../output/results.trx"__

**Comment by sitefinitysteve** [comment]
+1
Thanks!
